import React, { useState } from 'react';
import {
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as Haptics from 'expo-haptics';
import { useTheme } from '../contexts/ThemeContext';
import { ThemedBackground } from '../components/ThemedBackground';

function ExpandableSection({ title, children, theme }: { title: string; children: React.ReactNode; theme: any }) {
  const [open, setOpen] = useState(false);
  return (
    <View style={[styles.policyCard, { backgroundColor: theme.cardBackground, borderColor: theme.border }]}>
      <TouchableOpacity
        onPress={() => { Haptics.selectionAsync().catch(() => {}); setOpen(o => !o); }}
        activeOpacity={0.8}
        style={styles.policyHeader}
      >
        <Text style={[styles.policyTitle, { color: theme.text }]}>{title}</Text>
        <Text style={[styles.chevron, { color: theme.secondaryText }]}>{open ? '−' : '+'}</Text>
      </TouchableOpacity>
      {open && <View style={styles.policyBody}>{children}</View>}
    </View>
  );
}

export default function AboutScreen({ navigation }: any) {
  const { theme, isDarkMode } = useTheme();
  const insets = useSafeAreaInsets();

  return (
    <ThemedBackground style={{ flex: 1 }}>
      <StatusBar barStyle={theme.statusBar} translucent />
      <ScrollView
        contentContainerStyle={[styles.scroll, { paddingTop: insets.top + 20, paddingBottom: 40 }]}
        showsVerticalScrollIndicator={false}
      >
        <TouchableOpacity
          style={styles.backBtn}
          onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {}); navigation.goBack(); }}
          activeOpacity={0.7}
        >
          <Text style={[styles.backArrow, { color: theme.text }]}>{'←'}</Text>
        </TouchableOpacity>

        <Text style={[styles.title, { color: theme.text }]}>About Cerviced</Text>

        {/* Mission */}
        <View style={[styles.card, {
          backgroundColor: isDarkMode ? 'rgba(175,145,151,0.1)' : 'rgba(175,145,151,0.06)',
          borderColor: 'rgba(175,145,151,0.35)',
        }]}>
          <Text style={[styles.cardLabel, { color: theme.accent }]}>OUR MISSION</Text>
          <Text style={[styles.mission, { color: theme.text }]}>
            To make premium beauty and wellness services accessible to everyone — by connecting clients with skilled, independent professionals who deserve to be discovered.
          </Text>
        </View>

        {/* Vision */}
        <View style={[styles.card, { backgroundColor: theme.cardBackground, borderColor: theme.border }]}>
          <Text style={[styles.cardLabel, { color: theme.accent }]}>OUR VISION</Text>
          <Text style={[styles.body, { color: theme.secondaryText }]}>
            A world where finding your perfect stylist, nail tech, or aesthetician is as simple as opening an app. We champion the gig economy in beauty, giving independent talent the platform they deserve.
          </Text>
        </View>

        {/* App info */}
        <View style={[styles.card, { backgroundColor: theme.cardBackground, borderColor: theme.border }]}>
          <Text style={[styles.cardLabel, { color: theme.accent }]}>APP INFO</Text>
          <View style={styles.infoRow}>
            <Text style={[styles.infoKey, { color: theme.secondaryText }]}>Version</Text>
            <Text style={[styles.infoVal, { color: theme.text }]}>1.0.0</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={[styles.infoKey, { color: theme.secondaryText }]}>Build</Text>
            <Text style={[styles.infoVal, { color: theme.text }]}>2026.1</Text>
          </View>
        </View>

        {/* Privacy & Legal */}
        <Text style={[styles.section, { color: theme.accent }]}>PRIVACY & LEGAL</Text>

        <ExpandableSection title="Privacy Policy" theme={theme}>
          <Text style={[styles.policyText, { color: theme.secondaryText }]}>
            <Text style={[styles.policySubhead, { color: theme.text }]}>What we collect{'\n'}</Text>
            We collect information you provide directly — such as your name, email, phone number, and beauty preferences — and data generated by your use of the app, including bookings, searches, and interactions with providers.{'\n\n'}
            <Text style={[styles.policySubhead, { color: theme.text }]}>How we use it{'\n'}</Text>
            Your data is used to provide and personalise the Cerviced experience, process bookings, send notifications you've opted into, and improve our platform. We do not sell your personal data to third parties.{'\n\n'}
            <Text style={[styles.policySubhead, { color: theme.text }]}>Who we share it with{'\n'}</Text>
            We share necessary booking information with the provider you book with. We use trusted third-party services (e.g. Supabase for data storage, Expo for notifications) who process data on our behalf under strict agreements.{'\n\n'}
            <Text style={[styles.policySubhead, { color: theme.text }]}>Your rights{'\n'}</Text>
            You have the right to access, correct, or delete your data at any time. Contact us at privacy@cerviced.app. You may also request a full data export.{'\n\n'}
            <Text style={[styles.policySubhead, { color: theme.text }]}>Data retention{'\n'}</Text>
            We retain your account data for as long as your account is active. Deleted accounts are purged within 30 days, except where required by law.
          </Text>
        </ExpandableSection>

        <ExpandableSection title="Cookie Policy" theme={theme}>
          <Text style={[styles.policyText, { color: theme.secondaryText }]}>
            <Text style={[styles.policySubhead, { color: theme.text }]}>What are cookies?{'\n'}</Text>
            Cookies are small files stored on your device that help us recognise you and remember your preferences across sessions.{'\n\n'}
            <Text style={[styles.policySubhead, { color: theme.text }]}>Cookies we use{'\n'}</Text>
            <Text style={{ color: theme.text }}>Essential cookies</Text> — required for authentication and core app functionality. You cannot opt out of these.{'\n\n'}
            <Text style={{ color: theme.text }}>Preference cookies</Text> — remember your settings such as dark mode and notification preferences.{'\n\n'}
            <Text style={{ color: theme.text }}>Analytics cookies</Text> — help us understand how users interact with the app so we can improve it. These are anonymised and aggregated.{'\n\n'}
            <Text style={[styles.policySubhead, { color: theme.text }]}>Managing cookies{'\n'}</Text>
            You can clear cookies via your device settings at any time. Note that disabling essential cookies may affect your ability to log in or use certain features.{'\n\n'}
            <Text style={[styles.policySubhead, { color: theme.text }]}>Third-party cookies{'\n'}</Text>
            Our analytics and infrastructure partners may also set cookies. These are governed by their own policies. We do not permit advertising cookies on Cerviced.
          </Text>
        </ExpandableSection>

        <Text style={[styles.footer, { color: theme.secondaryText }]}>
          © 2026 Cerviced. All rights reserved.
        </Text>
      </ScrollView>
    </ThemedBackground>
  );
}

const styles = StyleSheet.create({
  bg: { flex: 1 },
  scroll: { paddingHorizontal: 24 },
  backBtn: { marginBottom: 24 },
  backArrow: { fontSize: 22, fontWeight: '900' },
  title: { fontFamily: 'BakbakOne-Regular', fontSize: 28, letterSpacing: 1, marginBottom: 24 },
  card: { borderRadius: 16, borderWidth: 0.5, padding: 18, marginBottom: 16, gap: 10 },
  cardLabel: { fontFamily: 'BakbakOne-Regular', fontSize: 11, letterSpacing: 2 },
  mission: { fontSize: 15, lineHeight: 23, fontStyle: 'italic' },
  body: { fontSize: 14, lineHeight: 21 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between' },
  infoKey: { fontSize: 13 },
  infoVal: { fontSize: 13, fontWeight: '600' },
  section: { fontFamily: 'BakbakOne-Regular', fontSize: 12, letterSpacing: 2, marginBottom: 12, marginTop: 8 },
  policyCard: { borderRadius: 14, borderWidth: 0.5, marginBottom: 10, overflow: 'hidden' },
  policyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16 },
  policyTitle: { fontSize: 15, fontWeight: '600' },
  chevron: { fontSize: 20, fontWeight: '300' },
  policyBody: { paddingHorizontal: 16, paddingBottom: 16 },
  policyText: { fontSize: 13, lineHeight: 20 },
  policySubhead: { fontWeight: '700', fontSize: 13 },
  footer: { fontSize: 12, textAlign: 'center', marginTop: 28 },
});
