#!/usr/bin/env node
/**
 * Obsidian vault generator.
 *
 * Regenerates the FACTUAL notes under docs/vault/auto/ straight from the code —
 * the lists that drift (screens, services + exports, contexts, and every DB
 * table / trigger / function / view / policy / cron job). The hand-written
 * narrative notes in docs/vault/ are never touched.
 *
 *   node scripts/gen-vault.mjs           # regenerate once
 *   node scripts/gen-vault.mjs --watch   # regenerate on every save
 *
 * Wired to run automatically via .githooks/pre-commit when src/ or supabase/
 * changes. Zero dependencies (Node built-ins only).
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, watch } from 'node:fs';
import { join, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'docs', 'vault', 'auto');

// ── tiny helpers ──────────────────────────────────────────────────────────────
const rel = (p) => p.split(ROOT + '/').pop();
const read = (p) => { try { return readFileSync(p, 'utf8'); } catch { return ''; } };
const exists = (p) => existsSync(p);

function lsFiles(dir, exts) {
  if (!exists(dir)) return [];
  return readdirSync(dir)
    .filter((f) => exts.some((e) => f.endsWith(e)))
    .sort((a, b) => a.localeCompare(b));
}

function allMatches(re, text) {
  const out = new Set();
  let m;
  const r = new RegExp(re.source, re.flags.includes('g') ? re.flags : re.flags + 'g');
  while ((m = r.exec(text))) out.add((m[1] ?? m[2] ?? '').trim());
  return [...out].filter(Boolean);
}

function exportsOf(src) {
  const fns = allMatches(/export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/, src);
  const consts = allMatches(/export\s+const\s+([A-Za-z0-9_]+)\s*[=:]/, src);
  return [...new Set([...fns, ...consts])].sort((a, b) => a.localeCompare(b));
}

// Recursively collect files (skips dotdirs, node_modules, tests, .d.ts).
function walk(dir, exts, acc = []) {
  if (!exists(dir)) return acc;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') || e.name === 'node_modules') continue;
    const full = join(dir, e.name);
    if (e.isDirectory()) walk(full, exts, acc);
    else if (exts.some((x) => e.name.endsWith(x)) && !/\.d\.ts$/.test(e.name) && !/\.test\./.test(e.name)) acc.push(full);
  }
  return acc.sort((a, b) => a.localeCompare(b));
}

// Every named function / arrow-const / memoized handler in a file.
function functionsOf(src) {
  const exp = new Set(exportsOf(src));
  const names = new Set();
  const add = (re) => allMatches(re, src).forEach((n) => names.add(n));
  add(/(?:export\s+)?(?:async\s+)?function\s+([A-Za-z0-9_]+)/);
  add(/const\s+([A-Za-z0-9_]+)\s*(?::[^=\n]+)?=\s*(?:async\s*)?\([^)]*\)\s*=>/);
  add(/const\s+([A-Za-z0-9_]+)\s*=\s*(?:async\s*)?[A-Za-z0-9_$]+\s*=>/);
  add(/const\s+([A-Za-z0-9_]+)\s*=\s*(?:React\.)?(?:useCallback|useMemo)\s*\(/);
  return { fns: [...names].sort((a, b) => a.localeCompare(b)), exp };
}

const BANNER = (extra = '') =>
  `> [!warning] Auto-generated by \`scripts/gen-vault.mjs\` — **do not edit by hand**.\n` +
  `> Run \`npm run vault\` (or just commit — the git hook refreshes it). ${extra}\n\n` +
  `#generated\n`;

function write(name, body) {
  if (!exists(OUT)) mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, name), body.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n');
}

// ── generators ────────────────────────────────────────────────────────────────
function genScreens() {
  const dir = join(ROOT, 'src', 'screens');
  const files = lsFiles(dir, ['.tsx']);
  const provider = files.filter((f) => /^Provider/.test(f));
  const client = files.filter((f) => !/^Provider/.test(f));
  const list = (arr) => arr.map((f) => `- \`src/screens/${f}\``).join('\n') || '- _(none)_';
  write('Screens (generated).md',
    `# Screens (generated)\n\n${BANNER()}\n` +
    `**${files.length} screens.** Curated overview: [[Screens & Navigation]].\n\n` +
    `## Provider (${provider.length})\n${list(provider)}\n\n` +
    `## Client / shared (${client.length})\n${list(client)}\n`);
  return files.length;
}

function genServices() {
  const dir = join(ROOT, 'src', 'services');
  const files = lsFiles(dir, ['.ts']);
  const sections = files.map((f) => {
    const ex = exportsOf(read(join(dir, f)));
    const body = ex.length ? ex.map((n) => `\`${n}\``).join(' · ') : '_no named exports_';
    return `### \`src/services/${f}\`\n${body}`;
  });
  write('Services (generated).md',
    `# Services (generated)\n\n${BANNER()}\n` +
    `**${files.length} service modules.** Curated overview: [[Services]].\n\n` +
    sections.join('\n\n') + '\n');
  return files.length;
}

function genContexts() {
  const dir = join(ROOT, 'src', 'contexts');
  const files = lsFiles(dir, ['.tsx', '.ts']);
  const rows = files.map((f) => `- \`src/contexts/${f}\` — ${exportsOf(read(join(dir, f))).map((n) => `\`${n}\``).join(', ') || '_—_'}`);
  write('Contexts (generated).md',
    `# Contexts (generated)\n\n${BANNER()}\n` +
    `**${files.length} contexts.** Curated overview: [[Contexts]].\n\n` +
    rows.join('\n') + '\n');
  return files.length;
}

function genRoutes() {
  const src = read(join(ROOT, 'src', 'navigation', 'types.ts'));
  const routes = allMatches(/^\s{2,}([A-Z][A-Za-z0-9]+)\s*:/m, src);
  write('Routes (generated).md',
    `# Routes (generated)\n\n${BANNER('Parsed from `src/navigation/types.ts`.')}\n` +
    `Curated overview: [[Screens & Navigation]].\n\n` +
    (routes.length ? routes.map((r) => `- \`${r}\``).join('\n') : '- _(could not parse — check types.ts)_') + '\n');
  return routes.length;
}

const SQL_KINDS = [
  ['Tables',   /CREATE TABLE (?:IF NOT EXISTS )?(?:public\.)?"?([A-Za-z0-9_]+)"?/i],
  ['Views',    /CREATE (?:OR REPLACE )?(?:MATERIALIZED )?VIEW (?:IF NOT EXISTS )?(?:public\.)?"?([A-Za-z0-9_]+)"?/i],
  ['Functions',/CREATE (?:OR REPLACE )?FUNCTION (?:public\.)?"?([A-Za-z0-9_]+)"?\s*\(/i],
  ['Triggers', /CREATE TRIGGER "?([A-Za-z0-9_]+)"?/i],
  ['Policies', /CREATE POLICY (?:"([^"]+)"|([A-Za-z0-9_]+))/i],
  ['Cron jobs',/cron\.schedule\(\s*'([^']+)'/i],
];
const BUNDLE = 'RUN_ALL_MIGRATIONS.sql';

function genDatabase() {
  const dir = join(ROOT, 'supabase');
  const files = lsFiles(dir, ['.sql']);
  // kind -> Map(name -> [files])
  const index = Object.fromEntries(SQL_KINDS.map(([k]) => [k, new Map()]));
  for (const f of files) {
    const txt = read(join(dir, f));
    for (const [kind, re] of SQL_KINDS) {
      for (const name of allMatches(re, txt)) {
        if (!index[kind].has(name)) index[kind].set(name, []);
        index[kind].get(name).push(f);
      }
    }
  }
  const home = (fs) => fs.find((x) => x !== BUNDLE) ?? fs[0];
  const counts = SQL_KINDS.map(([k]) => `- **${index[k].size}** ${k.toLowerCase()}`).join('\n');
  const section = ([kind]) => {
    const m = index[kind];
    if (!m.size) return `## ${kind}\n_(none)_`;
    const rows = [...m.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([name, fs]) => `- \`${name}\` — \`supabase/${home(fs)}\``);
    return `## ${kind} (${m.size})\n${rows.join('\n')}`;
  };
  write('Database Objects (generated).md',
    `# Database Objects (generated)\n\n${BANNER(`Scanned ${files.length} \`supabase/*.sql\` files.`)}\n` +
    `Curated overview: [[Data Layer — Supabase]]. "Defined in" skips the \`${BUNDLE}\` bundle when a dedicated file exists.\n\n` +
    `## Summary\n${counts}\n\n` +
    SQL_KINDS.map(section).join('\n\n') + '\n');
  return SQL_KINDS.reduce((n, [k]) => n + index[k].size, 0);
}

function genNavigation() {
  const dir = join(ROOT, 'src', 'screens');
  const files = lsFiles(dir, ['.tsx']);
  // from (component/file, minus .tsx) -> Set(target route names)
  const graph = new Map();
  const edges = new Set();
  for (const f of files) {
    const from = f.replace(/\.tsx$/, '');
    const targets = new Set(
      allMatches(/\.(?:navigate|push|replace)\(\s*['"]([A-Za-z][A-Za-z0-9]*)['"]/, read(join(dir, f)))
    );
    targets.delete(from); // ignore self-navigation noise
    if (targets.size) {
      graph.set(from, [...targets].sort((a, b) => a.localeCompare(b)));
      for (const t of targets) edges.add(`${from} --> ${t}`);
    }
  }
  const mermaid = edges.size
    ? '```mermaid\ngraph LR\n' + [...edges].sort().map((e) => '  ' + e).join('\n') + '\n```'
    : '_(no navigation calls found)_';
  const list = [...graph.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([from, tos]) => `- \`${from}\` → ${tos.map((t) => `\`${t}\``).join(', ')}`)
    .join('\n');
  write('Navigation Graph (generated).md',
    `# Navigation Graph (generated)\n\n${BANNER('Parsed from `navigation.navigate/push/replace(\'…\')` calls across `src/screens`.')}\n` +
    `**${edges.size} edges** across **${graph.size} screens**. Curated overview: [[Screens & Navigation]].\n\n` +
    `## Diagram\n> Dense is normal — pan/zoom, or read the list below.\n\n${mermaid}\n\n` +
    `## By screen\n${list || '_(none)_'}\n`);
  return edges.size;
}

function genFunctionIndex() {
  const files = walk(join(ROOT, 'src'), ['.ts', '.tsx']);
  const byFolder = new Map();
  let total = 0;
  for (const f of files) {
    const { fns, exp } = functionsOf(read(f));
    if (!fns.length) continue;
    total += fns.length;
    const relp = rel(f);
    const folder = dirname(relp);
    if (!byFolder.has(folder)) byFolder.set(folder, []);
    const marked = fns.map((n) => (exp.has(n) ? `**${n}**` : n)).join(' · ');
    byFolder.get(folder).push(`- \`${basename(relp)}\` — ${marked}`);
  }
  const body = [...byFolder.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([folder, rows]) => `### \`${folder}/\` (${rows.length})\n${rows.join('\n')}`)
    .join('\n\n');
  write('Function Index (generated).md',
    `# Function Index (generated)\n\n${BANNER('Every named function / arrow-const / memoized handler in `src`. **Bold** = exported.')}\n` +
    `**${total} functions** across **${files.length} files**.\n\n${body}\n`);
  return total;
}

const FEATURES = [
  ['Address release',        /address|full_address|address_release|client_bookings/i, 'Address Release'],
  ['Availability & slots',   /availab|\bslot|bookability|double.?book|buffer/i,       'Availability & Slots'],
  ['Payments',               /payment|deposit|stripe|balance|amount_paid|base_price|service_charge/i, 'Payments'],
  ['Booking flow',           /\bbooking|checkout|confirm/i,                           'Booking Flow'],
  ['Notifications',          /notif|expo.?push|push.?token|reminder/i,                'Notifications'],
  ['Provider onboarding',    /has_gone_live|go.?live|registration|onboard/i,          'Provider Onboarding & Go-Live'],
  ['Waitlist',               /waitlist/i,                                             'Booking Flow'],
  ['Reschedule / cancel',    /reschedul|cancel/i,                                     'Booking Flow'],
  ['Auth',                   /\bauth|session|sign.?in|sign.?out|password|biometric/i, 'Contexts'],
  ['Becca / AI',             /becca|aichat|assistant/i,                               'Services'],
  ['Cart & checkout',        /\bcart\b|checkout/i,                                    'Payments'],
];

function genFeatureMap() {
  const files = [
    ...walk(join(ROOT, 'src'), ['.ts', '.tsx']),
    ...lsFiles(join(ROOT, 'supabase'), ['.sql']).map((f) => join(ROOT, 'supabase', f)),
  ];
  const cache = files.map((f) => ({ f: rel(f), txt: read(f) }));
  const sections = FEATURES.map(([name, re, note]) => {
    const g = new RegExp(re.source, 'gi');
    const hits = cache
      .map(({ f, txt }) => ({ f, count: (txt.match(g) || []).length }))
      .filter((h) => h.count > 0)
      .sort((a, b) => b.count - a.count || a.f.localeCompare(b.f));
    const shown = hits.slice(0, 30).map((h) => `- \`${h.f}\` _(${h.count})_`).join('\n');
    const more = hits.length > 30 ? `\n- … +${hits.length - 30} more` : '';
    return `## ${name}\nCurated: [[${note}]] · **${hits.length} files**\n${shown || '_(none)_'}${more}`;
  });
  write('Feature Map (generated).md',
    `# Feature Map (generated)\n\n${BANNER('Where each concern lives — files mentioning a feature, ranked by match count. The "logic map".')}\n` +
    sections.join('\n\n') + '\n');
  return FEATURES.length;
}

function genTodos() {
  const files = walk(join(ROOT, 'src'), ['.ts', '.tsx']);
  const items = [];
  for (const f of files) {
    read(f).split('\n').forEach((ln, i) => {
      const m = ln.match(/\/\/\s*(TODO|FIXME|HACK|XXX)\b:?\s*(.*)/i);
      if (m) items.push({ f: rel(f), line: i + 1, kind: m[1].toUpperCase(), text: (m[2] || '').trim() });
    });
  }
  const byKind = {};
  for (const it of items) (byKind[it.kind] ||= []).push(it);
  const body = ['FIXME', 'TODO', 'HACK', 'XXX']
    .filter((k) => byKind[k])
    .map((k) => `## ${k} (${byKind[k].length})\n` + byKind[k].map((it) => `- \`${it.f}:${it.line}\` — ${it.text || '_(no text)_'}`).join('\n'))
    .join('\n\n');
  write('TODO Backlog (generated).md',
    `# TODO Backlog (generated)\n\n${BANNER('Scraped from `// TODO`, `// FIXME`, `// HACK`, `// XXX` comments in `src`.')}\n` +
    `**${items.length} items.**\n\n${body || '_No TODO/FIXME comments found. 🎉_'}\n`);
  return items.length;
}

function genIndex(stats) {
  write('Code Index.md',
    `# Code Index (generated)\n\n${BANNER()}\n` +
    `Live counts of the codebase. The generated detail notes below refresh on every commit that touches \`src/\` or \`supabase/\`.\n\n` +
    `| Area | Count | Detail | Curated |\n|---|---|---|---|\n` +
    `| Screens | ${stats.screens} | [[Screens (generated)]] | [[Screens & Navigation]] |\n` +
    `| Services | ${stats.services} | [[Services (generated)]] | [[Services]] |\n` +
    `| Contexts | ${stats.contexts} | [[Contexts (generated)]] | [[Contexts]] |\n` +
    `| Routes | ${stats.routes} | [[Routes (generated)]] | [[Screens & Navigation]] |\n` +
    `| Nav edges | ${stats.nav} | [[Navigation Graph (generated)]] | [[Screens & Navigation]] |\n` +
    `| DB objects | ${stats.db} | [[Database Objects (generated)]] | [[Data Layer — Supabase]] |\n` +
    `| Functions | ${stats.functions} | [[Function Index (generated)]] | — |\n` +
    `| Feature map | ${stats.features} | [[Feature Map (generated)]] | — |\n` +
    `| Code TODOs | ${stats.todos} | [[TODO Backlog (generated)]] | — |\n\n` +
    `Back to [[Home]].\n`);
}

function generateAll() {
  const stats = {
    screens: genScreens(),
    services: genServices(),
    contexts: genContexts(),
    routes: genRoutes(),
    nav: genNavigation(),
    db: genDatabase(),
    functions: genFunctionIndex(),
    features: genFeatureMap(),
    todos: genTodos(),
  };
  genIndex(stats);
  return stats;
}

// ── run ───────────────────────────────────────────────────────────────────────
const s = generateAll();
console.log(`vault: generated — ${s.screens} screens, ${s.services} services, ${s.contexts} contexts, ${s.routes} routes, ${s.nav} nav edges, ${s.db} db objects, ${s.functions} functions, ${s.todos} TODOs`);

if (process.argv.includes('--watch')) {
  console.log('vault: watching src/ and supabase/ … (Ctrl-C to stop)');
  let timer = null;
  const bounce = () => { clearTimeout(timer); timer = setTimeout(() => { try { generateAll(); console.log('vault: refreshed', new Date().toLocaleTimeString()); } catch (e) { console.error(e); } }, 250); };
  for (const d of ['src', 'supabase']) {
    const dir = join(ROOT, d);
    if (exists(dir)) watch(dir, { recursive: true }, bounce);
  }
}
