-- A booking reference people can actually quote, that is actually unique.
--
-- Until now there was no reference column at all. Five screens each derived
-- one from the primary key, four as `id.slice(0, 8)` and ProviderHomeScreen
-- as `id.replace(/-/g,'').substring(0, 10)` -- so the same appointment was
-- "34E82C04" to the client and "34E82C04E0" to the provider. That was fixed
-- app-side first (formatBookingRef), but agreeing on a truncation does not
-- make the truncation safe:
--
--   8 hex characters is a 4.29e9 space. By the birthday bound that is a 1%
--   chance of two bookings sharing a reference at ~9,300 bookings, and 50% at
--   ~77,000. For a marketplace those are not far-off numbers, and a support
--   desk where one reference can mean two appointments is a genuine incident.
--
-- So the reference becomes a real column with a real uniqueness guarantee,
-- rather than a display convention:
--
--   * Alphabet 23456789ABCDEFGHJKMNPQRSTVWXYZ -- 30 characters, Crockford
--     Base32's exclusions. No 0/O, no 1/I/L (indistinguishable read aloud or
--     handwritten), and no U (which is what stops a random code spelling
--     something unfortunate). This matters because the whole point of the
--     reference is that it survives being read down a phone line.
--   * Eight characters => 30^8 ~= 6.56e11. With a UNIQUE index the code is
--     never merely probably unique, so length only governs how often the
--     generator has to retry: at a million bookings the space is 0.00015%
--     full, so a retry is close to unheard of and the loop below is a
--     formality rather than a hot path.
--   * Random, not sequential. A sequential reference leaks total booking
--     volume to anyone holding two of them, which is business information
--     that does not belong on a client's receipt.
--   * Generated by a BEFORE INSERT trigger, so it is impossible to insert a
--     booking without one. Every producer gets it for free -- the cart claim
--     path, provider manual bookings, waitlist claims, and anything added
--     later that nobody remembers to update.
--
-- The `CRV-` prefix is display-only and is NOT stored, so the stored value
-- stays a clean sortable/searchable token and the presentation layer owns
-- how it looks (see formatBookingRef in src/features/bookings/presentation.ts).

-- --------------------------------------------------------------------------
-- 1. Column
-- --------------------------------------------------------------------------

ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS booking_ref TEXT;

-- --------------------------------------------------------------------------
-- 2. Generator
-- --------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.generate_booking_ref()
RETURNS TEXT
LANGUAGE plpgsql
VOLATILE
SET search_path TO 'public'
AS $function$
DECLARE
  v_alphabet CONSTANT TEXT := '23456789ABCDEFGHJKMNPQRSTVWXYZ';
  v_len      CONSTANT INT  := 8;
  v_code     TEXT;
  v_attempt  INT := 0;
BEGIN
  LOOP
    v_code := '';
    FOR i IN 1..v_len LOOP
      -- floor(random()*30) + 1 -> 1..30, substr is 1-indexed.
      v_code := v_code || substr(v_alphabet, floor(random() * length(v_alphabet))::int + 1, 1);
    END LOOP;

    EXIT WHEN NOT EXISTS (
      SELECT 1 FROM public.bookings WHERE booking_ref = v_code
    );

    v_attempt := v_attempt + 1;
    -- The UNIQUE index is the real guarantee; this pre-check just avoids
    -- burning an insert on a known clash. If we somehow cannot find a free
    -- code in 50 tries the space is far fuller than it should ever be, and
    -- failing loudly beats looping forever.
    IF v_attempt >= 50 THEN
      RAISE EXCEPTION 'Could not generate a unique booking reference after % attempts', v_attempt;
    END IF;
  END LOOP;

  RETURN v_code;
END;
$function$;

-- --------------------------------------------------------------------------
-- 3. Backfill before the constraint, so existing rows are not rejected
-- --------------------------------------------------------------------------

DO $backfill$
DECLARE
  r RECORD;
BEGIN
  FOR r IN SELECT id FROM public.bookings WHERE booking_ref IS NULL LOOP
    UPDATE public.bookings
       SET booking_ref = public.generate_booking_ref()
     WHERE id = r.id;
  END LOOP;
END;
$backfill$;

-- --------------------------------------------------------------------------
-- 4. Uniqueness, then NOT NULL
-- --------------------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS bookings_booking_ref_key
  ON public.bookings (booking_ref);

ALTER TABLE public.bookings
  ALTER COLUMN booking_ref SET NOT NULL;

-- --------------------------------------------------------------------------
-- 5. Trigger, so no producer can insert without one
-- --------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_booking_ref()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.booking_ref IS NULL THEN
    NEW.booking_ref := public.generate_booking_ref();
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_set_booking_ref ON public.bookings;
CREATE TRIGGER trg_set_booking_ref
  BEFORE INSERT ON public.bookings
  FOR EACH ROW
  EXECUTE FUNCTION public.set_booking_ref();

-- --------------------------------------------------------------------------
-- 6. Grants
-- --------------------------------------------------------------------------
-- generate_booking_ref reads the bookings table to check for a clash, so it
-- is not something a client should be able to call directly.

REVOKE ALL ON FUNCTION public.generate_booking_ref() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_booking_ref() FROM PUBLIC, anon, authenticated;
